(() => {
'use strict';
const COURSE=window.CODE_LIFE_COURSE||[], TRACKS=window.CODE_LIFE_TRACKS||{}, PROJECTS=window.CODE_LIFE_PROJECTS||[];
const app=document.getElementById('app'), crumb=document.getElementById('crumb-title'), topStreak=document.getElementById('top-streak'), accountBtn=document.getElementById('top-account'), toastEl=document.getElementById('toast');
const KEY='code-life-state-v1';
const fresh=()=>({name:'Bri',completed:[],drafts:{},streak:0,lastCompletedDate:null,playground:{html:'<h1>Code Life</h1>\n<p>I am learning to build websites.</p>',css:'body {\n  font-family: sans-serif;\n  padding: 24px;\n}\nh1 { color: royalblue; }',js:'console.log("My code is running!");'}});
let state=load(), tab='learn', practicePassed={}, quizChoice={}, db=null, user=null, cloudReady=false;
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');return Object.assign(fresh(),p||{},{playground:Object.assign(fresh().playground,p?.playground||{})});}catch{return fresh();}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));chrome();}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function today(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function yesterday(){const d=new Date();d.setDate(d.getDate()-1);return today(d);}
function lessons(track){return COURSE.filter(l=>l.track===track)}
function done(id){return state.completed.includes(id)}
function trackUnlocked(track){if(track==='html')return true;if(track==='css')return lessons('html').every(l=>done(l.id));if(track==='js')return lessons('css').every(l=>done(l.id));return false;}
function lessonUnlocked(lesson){if(!trackUnlocked(lesson.track))return false;const a=lessons(lesson.track),i=a.findIndex(l=>l.id===lesson.id);return i<=0||done(a[i-1].id)}
function progress(track){const a=lessons(track), d=a.filter(l=>done(l.id)).length;return{done:d,total:a.length,pct:a.length?Math.round(d/a.length*100):0}}
function totalProgress(){const d=COURSE.filter(l=>done(l.id)).length;return{done:d,total:COURSE.length,pct:COURSE.length?Math.round(d/COURSE.length*100):0}}
function nextLesson(){return COURSE.find(l=>lessonUnlocked(l)&&!done(l.id))||null}
function chrome(){topStreak.textContent=`✦ ${state.streak||0} day${state.streak===1?'':'s'} streak`;accountBtn.textContent=(state.name||user?.email||'B').trim().charAt(0).toUpperCase()||'B'}
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),2100)}
function nav(page){document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
function route(v){location.hash='#'+v}
function courseCard(track){const m=TRACKS[track],p=progress(track),u=trackUnlocked(track);return `<article class="course-card ${u?'':'locked'}"><div class="course-card-icon">${m.emoji}</div><h3>${m.name}</h3><p>${m.sub} · ${m.description}</p><div class="course-bottom"><div class="course-progress"><span>${u?`${p.done}/${p.total} lessons`:'Locked'}</span><span>${u?`${p.pct}%`:'🔒'}</span></div><div class="progress-track"><div class="progress-fill" style="width:${u?p.pct:0}%"></div></div><button class="btn btn-soft btn-full" style="margin-top:13px" data-track="${track}" ${u?'':'disabled'}>${p.done?'Continue':'Start'} ${m.name}</button></div></article>`}
function renderHome(){nav('home');crumb.textContent='Home';const t=totalProgress(),n=nextLesson();app.innerHTML=`<section class="hero"><div><span class="hero-tag">LEARN · CODE · CREATE</span><h2>Build real coding skills,<br>one tiny win at a time.</h2><p>Start with HTML, style it with CSS, then make it interactive with JavaScript. No confusing jumps.</p><button class="btn btn-white" data-next>${n?`Continue: ${esc(n.title)}`:'Course complete ✦'}</button></div><div class="hero-deco">&lt;/&gt;</div></section><section class="stats"><div class="stat"><span class="stat-icon">✓</span><div><h3>${t.done}</h3><small>LESSONS DONE</small></div></div><div class="stat"><span class="stat-icon">✦</span><div><h3>${state.streak||0}</h3><small>DAY STREAK</small></div></div><div class="stat"><span class="stat-icon">↗</span><div><h3>${t.pct}%</h3><small>TOTAL PROGRESS</small></div></div></section><div class="row"><h2 class="section-title">Your learning path</h2><button class="back-link" data-go="learn">See all lessons →</button></div><section class="course-grid">${['html','css','js'].map(courseCard).join('')}</section><section class="section-block"><h2 class="section-title">Up next</h2>${n?`<div class="next"><div><div class="small-cap">${TRACKS[n.track].name} · ${n.time} MIN</div><h3>${esc(n.title)}</h3><p>${esc(n.concept)}</p></div><button class="btn btn-primary" data-lesson="${n.id}">Start lesson →</button></div>`:`<div class="complete-screen"><div class="big-star">✦</div><h2>You finished Code Life!</h2><p>All starter lessons are complete. Now build the mini projects.</p><button class="btn btn-primary" data-go="profile">See projects</button></div>`}</section>`}
function lessonRow(l,i){const u=lessonUnlocked(l),d=done(l.id);return `<button class="lesson-row ${d?'done':''}" data-lesson="${l.id}" ${u?'':'disabled'}><span class="lesson-count">${d?'✓':i+1}</span><span><strong>${esc(l.title)}</strong><small>${l.time} min · ${d?'Completed':u?'Ready':'Locked'}</small></span><span class="lesson-arrow">${u?'›':'🔒'}</span></button>`}
function renderLearn(){nav('learn');crumb.textContent='My courses';app.innerHTML=`<div class="eyebrow">YOUR ROADMAP</div><h1 class="page-title">HTML → CSS → JavaScript</h1><p class="subheading">Each lesson unlocks the next one. Finish a full track to unlock the following language.</p><section class="course-grid" style="margin-top:24px">${['html','css','js'].map(courseCard).join('')}</section><section class="section-block card-stack">${['html','css','js'].map(track=>{const m=TRACKS[track],u=trackUnlocked(track);return `<div class="panel"><div class="row"><div><div class="small-cap">${m.name}</div><h2 class="section-title" style="margin:6px 0">${m.sub}</h2></div><span>${u?`${progress(track).pct}%`:'🔒'}</span></div>${u?lessons(track).map(lessonRow).join(''):'<p class="subheading">Finish the previous track to unlock these lessons.</p>'}</div>`}).join('')}</section>`}
function renderTrack(track){const m=TRACKS[track];if(!m||!trackUnlocked(track))return renderLearn();nav('learn');crumb.textContent=m.name;const p=progress(track);app.innerHTML=`<button class="back-link" data-go="learn">← My courses</button><div class="track-header"><div class="course-card-icon">${m.emoji}</div><div><div class="small-cap">${p.done}/${p.total} LESSONS · ${p.pct}%</div><h2>${m.name}</h2><p>${m.description}</p></div></div><div class="lesson-list">${lessons(track).map(lessonRow).join('')}</div>`}
function panel(l){if(done(l.id)&&tab==='quiz'){const n=nextLesson();return `<div class="complete-screen"><div class="big-star">✦</div><h2>Lesson complete!</h2><p>You unlocked the next step.</p>${n?`<button class="btn btn-primary" data-lesson="${n.id}">Next: ${esc(n.title)} →</button>`:`<button class="btn btn-primary" data-go="profile">See your progress</button>`}</div>`}if(tab==='learn')return `<div class="lesson-copy"><p>${esc(l.concept)}</p><div class="code-window"><div class="code-title">EXAMPLE</div><pre><code>${esc(l.example)}</code></pre></div><p>${esc(l.explain)}</p><div class="tip"><strong>Remember:</strong> You do not need to memorize every character. Learn what each part does.</div><div class="row"><span></span><button class="btn btn-primary" data-tab="practice">Try it yourself →</button></div></div>`;if(tab==='practice'){const code=state.drafts[l.id]??l.starter;return `<div class="panel"><div class="small-cap">YOUR CHALLENGE</div><h2 class="section-title" style="margin-top:7px">${esc(l.task)}</h2><p class="subheading">Hint: ${esc(l.hint)}</p><div class="code-window"><div class="editor-toolbar"><span>${TRACKS[l.track].name} editor</span><span>autosaves</span></div><textarea id="lesson-editor" class="editor" data-draft="${l.id}" spellcheck="false">${esc(code)}</textarea></div><div class="workspace-actions"><button class="btn btn-outline" data-run="${l.id}">▶ Run code</button><button class="btn btn-primary" data-check="${l.id}">Check my answer ✓</button></div><div id="lesson-feedback"></div><div class="preview-wrap"><div class="preview-card"><div class="preview-head">PREVIEW</div><iframe id="lesson-preview" class="preview-frame" sandbox="allow-scripts" title="Code preview"></iframe></div><div class="preview-card"><div class="preview-head">CONSOLE</div><pre id="lesson-console" class="console-output">Run your code to see output here.</pre></div></div></div>`}const choice=quizChoice[l.id];return `<div class="panel"><div class="small-cap">QUICK CHECK</div><h2 class="section-title" style="margin-top:8px">${esc(l.quiz.q)}</h2><div class="quiz-options">${l.quiz.options.map((o,i)=>`<button class="quiz-option ${choice===i?'selected':''}" data-choice="${i}" data-id="${l.id}">${esc(o)}</button>`).join('')}</div><div id="quiz-feedback"></div><button class="btn btn-primary" data-submit="${l.id}" ${choice===undefined?'disabled':''}>Check answer</button></div>`}
function renderLesson(id){const l=COURSE.find(x=>x.id===id);if(!l||!lessonUnlocked(l))return renderLearn();nav('learn');crumb.textContent=l.title;const arr=lessons(l.track),i=arr.findIndex(x=>x.id===id),passed=practicePassed[id]||done(id);app.innerHTML=`<button class="back-link" data-track="${l.track}">← ${TRACKS[l.track].name} lessons</button><div class="lesson-main"><div class="lesson-top"><div><div class="step-label">${TRACKS[l.track].name.toUpperCase()} · LESSON ${i+1} OF ${arr.length}</div><h1 class="lesson-title">${esc(l.title)}</h1></div><span class="tiny-meta">~${l.time} min</span></div><div class="lesson-tabs"><button class="lesson-tab ${tab==='learn'?'selected':''}" data-tab="learn">1. Learn</button><button class="lesson-tab ${tab==='practice'?'selected':''}" data-tab="practice">2. Practice</button><button class="lesson-tab ${tab==='quiz'?'selected':''}" data-tab="quiz" ${passed?'':'disabled'}>3. Quiz</button></div><div>${panel(l)}</div></div>`}
function sandbox(html='',css='',js=''){const safe=String(js).replace(/<\/script/gi,'<\\/script');return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:;"><style>body{font-family:system-ui,sans-serif;padding:18px;color:#20304f}${css}</style><script>(function(){const send=(level,args)=>parent.postMessage({type:'code-life-console',level,args:Array.from(args).map(v=>{try{return typeof v==='string'?v:JSON.stringify(v)}catch{return String(v)}})},'*');['log','warn','error'].forEach(level=>{const old=console[level];console[level]=function(){send(level,arguments);old.apply(console,arguments)}});window.onerror=m=>send('error',[m])})();<\/script></head><body>${html}<script>try{${safe}}catch(e){console.error(e.message)}<\/script></body></html>`}
function runLesson(id){const l=COURSE.find(x=>x.id===id),e=document.getElementById('lesson-editor'),f=document.getElementById('lesson-preview'),o=document.getElementById('lesson-console');if(!l||!e||!f)return;if(o)o.textContent='Running…';const c=e.value;if(l.track==='html')f.srcdoc=sandbox(c);else if(l.track==='css')f.srcdoc=sandbox('<h1>Code Life</h1><p class="highlight">Practice makes progress.</p><div class="card"><strong>Sample card</strong><div class="row"><button>One</button><button>Two</button></div></div>',c);else f.srcdoc=sandbox('<h1>JavaScript Lab</h1><button>Click me</button><p>Watch the console panel.</p>','',c)}
function feedback(id,m,k='info'){const e=document.getElementById(id);if(e)e.innerHTML=`<div class="feedback ${k}">${esc(m)}</div>`}
function checkLesson(id){const l=COURSE.find(x=>x.id===id),e=document.getElementById('lesson-editor');if(!l||!e)return;state.drafts[id]=e.value;save();for(const r of l.rules){const re=new RegExp(r.value,r.flags||'');if(!re.test(e.value)){practicePassed[id]=false;feedback('lesson-feedback',`${r.message} Hint: ${l.hint}`,'bad');return}}practicePassed[id]=true;feedback('lesson-feedback','Yes! Your code matches the challenge. Quiz unlocked ✦','good');runLesson(id);setTimeout(()=>{tab='quiz';renderLesson(id)},600)}
function complete(id){if(!done(id))state.completed.push(id);const t=today();if(state.lastCompletedDate!==t){state.streak=state.lastCompletedDate===yesterday()?(state.streak||0)+1:1;state.lastCompletedDate=t}save();syncCloud().catch(()=>{})}
function submitQuiz(id){const l=COURSE.find(x=>x.id===id),c=quizChoice[id];if(!l||c===undefined)return;if(c!==l.quiz.answer){feedback('quiz-feedback','Not quite. Try another answer.','bad');return}complete(id);feedback('quiz-feedback',l.quiz.why,'good');toast('Lesson complete! ✦');setTimeout(()=>renderLesson(id),450)}
function renderPlayground(){nav('playground');crumb.textContent='Playground';app.innerHTML=`<div class="eyebrow">FREE PRACTICE</div><h1 class="page-title">Your coding playground</h1><p class="subheading">Experiment here without affecting your lesson progress.</p><div class="card-stack"><div class="playground-surface"><div class="editor-toolbar"><span>HTML</span></div><textarea class="editor" data-play="html" spellcheck="false">${esc(state.playground.html)}</textarea></div><div class="playground-surface"><div class="editor-toolbar"><span>CSS</span></div><textarea class="editor" data-play="css" spellcheck="false">${esc(state.playground.css)}</textarea></div><div class="playground-surface"><div class="editor-toolbar"><span>JavaScript</span></div><textarea class="editor" data-play="js" spellcheck="false">${esc(state.playground.js)}</textarea></div></div><div class="workspace-actions" style="margin:15px 0"><button class="btn btn-primary" data-run-play>▶ Run everything</button><button class="btn btn-outline" data-reset-play>Reset</button></div><div class="preview-wrap"><div class="preview-card"><div class="preview-head">LIVE PREVIEW</div><iframe id="play-preview" class="preview-frame" style="min-height:280px" sandbox="allow-scripts"></iframe></div><div class="preview-card"><div class="preview-head">CONSOLE</div><pre id="play-console" class="console-output" style="min-height:280px">Press Run everything.</pre></div></div>`}
function runPlay(){const f=document.getElementById('play-preview'),o=document.getElementById('play-console');if(o)o.textContent='Running…';if(f)f.srcdoc=sandbox(state.playground.html,state.playground.css,state.playground.js)}
function badgeData(){const t=totalProgress().done,h=progress('html'),c=progress('css'),j=progress('js');return [['🌱','First line','Complete your first lesson',t>=1],['🏗️','Structure star','Complete HTML',h.done===h.total],['🎨','Style maker','Complete CSS',c.done===c.total],['⚡','JS starter','Complete JavaScript',j.done===j.total],['🔥','On a roll','Reach a 3-day streak',state.streak>=3],['🏆','Code Life grad','Complete all lessons',t===COURSE.length]]}
function renderProfile(){nav('profile');crumb.textContent='My progress';const p=totalProgress();app.innerHTML=`<div class="eyebrow">YOUR PROGRESS</div><h1 class="page-title">Look how far you’ve come.</h1><section class="panel profile-top"><div class="profile-avatar">${esc((state.name||'B').charAt(0).toUpperCase())}</div><div><h2 style="margin:0 0 5px">${esc(state.name||'Bri')}</h2><p class="subheading" style="margin:0 0 8px">${p.done}/${p.total} lessons complete · ${p.pct}%</p><div class="progress-track"><div class="progress-fill" style="width:${p.pct}%"></div></div></div></section><section class="section-block"><div class="row"><h2 class="section-title">Achievements</h2><span class="tiny-meta">${badgeData().filter(b=>b[3]).length}/6 unlocked</span></div><div class="badge-grid">${badgeData().map(b=>`<div class="achievement ${b[3]?'':'locked'}"><div class="achievement-icon">${b[0]}</div><strong>${b[1]}</strong><small>${b[2]}</small></div>`).join('')}</div></section><section class="section-block"><h2 class="section-title">Mini projects</h2><div class="course-grid">${PROJECTS.map(x=>`<article class="project-card"><div class="small-cap">${x.track.toUpperCase()} PROJECT</div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><ul>${x.requirements.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></article>`).join('')}</div></section><section class="section-block panel"><div class="row"><div><h2 class="section-title" style="margin-bottom:4px">Cloud account</h2><p class="subheading" style="margin:0">${user?`Signed in as ${esc(user.email)}`:cloudReady?'Sign in to sync across devices.':'Guest mode works now. Connect Supabase later for syncing.'}</p></div><button class="btn btn-soft" data-go="account">${user?'Manage':'Account'}</button></div></section>`}
function renderAccount(){nav('profile');crumb.textContent='Account';if(!cloudReady){app.innerHTML=`<button class="back-link" data-go="profile">← My progress</button><div class="panel auth-box"><div class="eyebrow">GUEST MODE</div><h1 class="page-title">Your lessons still work.</h1><p class="auth-note">Supabase is not connected yet, so your progress is saved on this device. Add your public Project URL and publishable key in <strong>supabase-config.js</strong> when you want cloud accounts.</p></div>`;return}if(user){app.innerHTML=`<button class="back-link" data-go="profile">← My progress</button><div class="panel auth-box"><div class="eyebrow">SIGNED IN</div><h1 class="page-title">Cloud sync is on.</h1><p class="auth-note">${esc(user.email)}</p><button class="btn btn-danger" data-signout>Sign out</button></div>`;return}app.innerHTML=`<button class="back-link" data-go="profile">← My progress</button><div class="panel auth-box"><div class="eyebrow">CODE LIFE ACCOUNT</div><h1 class="page-title">Keep your progress with you.</h1><p class="auth-note">Use email and password. If Supabase email confirmation is enabled, confirm the email before signing in.</p><div class="form-field"><label>Email</label><input id="auth-email" type="email" autocomplete="email" placeholder="you@example.com"></div><div class="form-field"><label>Password</label><input id="auth-password" type="password" autocomplete="current-password" minlength="6" placeholder="At least 6 characters"></div><div id="auth-feedback"></div><div class="workspace-actions"><button class="btn btn-primary" data-signin>Sign in</button><button class="btn btn-outline" data-signup>Create account</button></div></div>`}
function render(){const h=(location.hash||'#home').slice(1);if(h.startsWith('lesson-'))return renderLesson(h.replace('lesson-',''));if(h.startsWith('track-'))return renderTrack(h.replace('track-',''));if(h==='learn')return renderLearn();if(h==='playground')return renderPlayground();if(h==='profile')return renderProfile();if(h==='account')return renderAccount();return renderHome()}
async function initSupabase(){const c=window.CODE_LIFE_SUPABASE||{};if(!window.supabase||!c.url||!c.publishableKey)return;try{db=window.supabase.createClient(c.url,c.publishableKey);cloudReady=true;const {data}=await db.auth.getSession();user=data?.session?.user||null;if(user)await mergeCloud();db.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user)await mergeCloud();chrome();if((location.hash||'').includes('account')||(location.hash||'').includes('profile'))render()})}catch(e){console.warn(e);cloudReady=false}}
async function mergeCloud(){if(!db||!user)return;const {data,error}=await db.from('code_life_progress').select('*').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data){state.completed=[...new Set([...(state.completed||[]),...(data.completed_lesson_ids||[])])];state.streak=Math.max(state.streak||0,data.streak||0);if(data.last_active_on&&(!state.lastCompletedDate||data.last_active_on>state.lastCompletedDate))state.lastCompletedDate=data.last_active_on;save()}await syncCloud()}
async function syncCloud(){if(!db||!user)return;const {error}=await db.from('code_life_progress').upsert({user_id:user.id,completed_lesson_ids:state.completed||[],last_active_on:state.lastCompletedDate,streak:state.streak||0,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error}
async function auth(mode){if(!db)return;const email=document.getElementById('auth-email')?.value.trim(),password=document.getElementById('auth-password')?.value||'';if(!email||password.length<6){feedback('auth-feedback','Enter a valid email and a password with at least 6 characters.','bad');return}feedback('auth-feedback','Working…','info');const r=mode==='signup'?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(r.error){feedback('auth-feedback',r.error.message,'bad');return}if(mode==='signup'&&!r.data.session){feedback('auth-feedback','Account created. Check your email to confirm it, then sign in.','good');return}user=r.data.user;await mergeCloud();toast('Signed in and synced ✦');route('profile')}
document.addEventListener('click',async e=>{const x=e.target.closest('button,a');if(!x)return;if(x.dataset.go)return route(x.dataset.go);if(x.dataset.track)return route('track-'+x.dataset.track);if(x.dataset.lesson){tab='learn';return route('lesson-'+x.dataset.lesson)}if(x.hasAttribute('data-next')){const n=nextLesson();return n?route('lesson-'+n.id):route('profile')}if(x.dataset.tab){tab=x.dataset.tab;const id=(location.hash||'').replace('#lesson-','');return renderLesson(id)}if(x.dataset.run)return runLesson(x.dataset.run);if(x.dataset.check)return checkLesson(x.dataset.check);if(x.dataset.choice!==undefined){quizChoice[x.dataset.id]=Number(x.dataset.choice);return renderLesson(x.dataset.id)}if(x.dataset.submit)return submitQuiz(x.dataset.submit);if(x.hasAttribute('data-run-play'))return runPlay();if(x.hasAttribute('data-reset-play')){state.playground=fresh().playground;save();return renderPlayground()}if(x.hasAttribute('data-signin'))return auth('signin');if(x.hasAttribute('data-signup'))return auth('signup');if(x.hasAttribute('data-signout')&&db){await db.auth.signOut();user=null;toast('Signed out');renderAccount()}})
document.addEventListener('input',e=>{if(e.target.dataset?.draft){state.drafts[e.target.dataset.draft]=e.target.value;save()}if(e.target.dataset?.play){state.playground[e.target.dataset.play]=e.target.value;save()}})
window.addEventListener('message',e=>{if(!e.data||e.data.type!=='code-life-console')return;const out=document.getElementById('lesson-console')||document.getElementById('play-console');if(!out)return;if(out.textContent==='Running…'||out.textContent.startsWith('Run your')||out.textContent.startsWith('Press Run'))out.textContent='';out.textContent+=`${e.data.level==='error'?'⚠ ':''}${(e.data.args||[]).join(' ')}\n`})
window.addEventListener('hashchange',render);accountBtn.addEventListener('click',()=>route('account'));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));chrome();render();initSupabase().then(()=>{chrome();if((location.hash||'').includes('account'))render()})
})();
